"""
Test C++ layer implementations against PyTorch reference outputs.

This script loads reference outputs generated by generate_pytorch_reference.py
and compares them against C++ layer-by-layer implementations.
"""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path
from typing import Dict, Optional

import torch
import numpy as np

from src.misc import lb


def load_reference(path: Path) -> Dict[str, torch.Tensor]:
    """Load reference outputs from pickle file."""
    with open(path, 'rb') as f:
        return pickle.load(f)


def load_checkpoint_weights(checkpoint_path: Path, agent_key: str = 'self') -> Dict[str, torch.Tensor]:
    """Load model weights from checkpoint."""
    checkpoint = torch.load(checkpoint_path, map_location='cpu')

    if 'policy_nets' in checkpoint and agent_key in checkpoint['policy_nets']:
        return checkpoint['policy_nets'][agent_key]
    elif 'model_state_dict' in checkpoint:
        return checkpoint['model_state_dict']
    else:
        raise ValueError(f"Could not find model state dict in checkpoint (keys: {list(checkpoint.keys())})")


def pad_model_weights(model_state_dict: Dict[str, torch.Tensor], pad_obs_to: int = 16) -> Dict[str, torch.Tensor]:
    """
    Pad observation encoder weights for CUDA alignment.

    Args:
        model_state_dict: Model state dictionary
        pad_obs_to: Target dimension for padding (default 16)

    Returns:
        Modified state dict with padded weights
    """
    # Pad obs_encoder.0.weight from [hidden_dim, obs_dim] to [hidden_dim, pad_obs_to]
    obs_linear_weight_key = "obs_encoder.0.weight"
    if obs_linear_weight_key in model_state_dict:
        weight = model_state_dict[obs_linear_weight_key]
        hidden_dim, obs_dim = weight.shape

        if obs_dim < pad_obs_to:
            # Pad with zeros
            padding = torch.zeros(hidden_dim, pad_obs_to - obs_dim, dtype=weight.dtype, device=weight.device)
            padded_weight = torch.cat([weight, padding], dim=1)
            model_state_dict[obs_linear_weight_key] = padded_weight
            print(f"Padded {obs_linear_weight_key} from [{hidden_dim}, {obs_dim}] to [{hidden_dim}, {pad_obs_to}]")

    return model_state_dict


def prepare_batched_weights(
    state_dict: Optional[Dict[str, torch.Tensor]],
    num_layers: int = 2,
    num_experts: int = 8,
    device: str = 'cpu',
    state_dict2: Optional[Dict[str, torch.Tensor]] = None,
) -> Dict[str, torch.Tensor]:
    """
    Prepare batched weights for C++ testing.

    For single-policy testing, we add a batch dimension to all weights.
    Also pre-stacks MoE expert weights and creates pointer tensors.
    """
    # First, prestack MoE expert weights (must be done before adding batch dim)
    print(f"Pre-stacking MoE expert weights ({num_layers} layers, {num_experts} experts)...")
    if state_dict2 is None:
        state_dict_stacked = lb.prestack_moe_expert_weights(state_dict, num_layers, num_experts)
        batched: Dict[str, torch.Tensor] = {}
        for key, value in state_dict_stacked.items():
            # Add batch dimension [1, ...] and move to device
            t = value.unsqueeze(0).to(device)
            batched[key] = t
    else:
        # Two-policy: prestack individually then stack across policies
        sd1 = lb.prestack_moe_expert_weights(dict(state_dict), num_layers, num_experts)
        sd2 = lb.prestack_moe_expert_weights(dict(state_dict2), num_layers, num_experts)
        batched = lb.batch_state_dicts([sd1, sd2])
        for k in list(batched.keys()):
            batched[k] = batched[k].to(device)

    # If using CUDA, convert floating-point weights to FP16 before creating
    # MoE pointer tensors so that GPU kernels (which expect Half) match dtype.
    if device.startswith('cuda'):
        for key, tensor in list(batched.items()):
            if tensor.is_floating_point():
                batched[key] = tensor.to(torch.float16).contiguous()

    # Create MoE weight pointers (must be done after moving to device)
    print("Creating MoE weight pointers...")
    batched_with_ptrs = lb.create_moe_weight_pointers(batched, num_layers, num_experts)

    # Add fixed buffers (action decomposition LUTs)
    batched_final = lb.add_fixed_buffers(batched_with_ptrs, device)

    return batched_final


def compare_tensors(
    name: str,
    cpp_output: torch.Tensor,
    pytorch_output: torch.Tensor,
    rtol: float = 1e-3,
    atol: float = 1e-4
) -> bool:
    """
    Compare two tensors and report statistics.

    Returns:
        True if tensors match within tolerance, False otherwise
    """
    # Move to CPU and convert to float32 for comparison
    cpp_np = cpp_output.detach().cpu().float().numpy()
    pytorch_np = pytorch_output.detach().cpu().float().numpy()

    # Check shapes
    if cpp_np.shape != pytorch_np.shape:
        print(f"[FAIL] {name}: Shape mismatch! C++: {cpp_np.shape}, PyTorch: {pytorch_np.shape}")
        return False

    # Compute errors
    abs_diff = np.abs(cpp_np - pytorch_np)
    rel_diff = abs_diff / (np.abs(pytorch_np) + 1e-8)

    max_abs_error = np.max(abs_diff)
    mean_abs_error = np.mean(abs_diff)
    max_rel_error = np.max(rel_diff)
    mean_rel_error = np.mean(rel_diff)

    # Check if within tolerance
    matches = np.allclose(cpp_np, pytorch_np, rtol=rtol, atol=atol)

    status = "PASS" if matches else "FAIL"
    print(f"[{status}] {name}:")
    print(f"  Shape: {cpp_np.shape}")
    print(f"  Max abs error: {max_abs_error:.6e}")
    print(f"  Mean abs error: {mean_abs_error:.6e}")
    print(f"  Max rel error: {max_rel_error:.6e}")
    print(f"  Mean rel error: {mean_rel_error:.6e}")

    if not matches:
        # Print some mismatched values
        mismatch_mask = abs_diff > (atol + rtol * np.abs(pytorch_np))
        mismatch_indices = np.where(mismatch_mask)
        num_mismatches = len(mismatch_indices[0])
        print(f"  Number of mismatches: {num_mismatches} / {cpp_np.size} ({100 * num_mismatches / cpp_np.size:.2f}%)")

        if num_mismatches > 0:
            # Show first few mismatches
            num_show = min(5, num_mismatches)
            print(f"  First {num_show} mismatches:")
            for i in range(num_show):
                idx = tuple(ind[i] for ind in mismatch_indices)
                print(f"    [{idx}] C++: {cpp_np[idx]:.6f}, PyTorch: {pytorch_np[idx]:.6f}, Diff: {abs_diff[idx]:.6e}")

    return matches


def test_action_decomposition(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu'
) -> bool:
    """Test action decomposition layer."""
    print("\n" + "=" * 80)
    print("Testing Action Decomposition")
    print("=" * 80)

    # Get inputs from reference
    action_sequence = reference['input/action_sequence'].to(device)
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    # Policy indices (single policy, index 0)
    batch_size = action_sequence.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    act_kind_ids_cpp, count_ids_cpp, table_flag_ids_cpp = lb.test_action_decomposition(
        action_sequence,
        batched_weights,
        policy_indices,
        padding_mask,
        count_pad=4,
        tflag_pad=3
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("act_kind_ids", act_kind_ids_cpp, reference['decompose/act_kind_ids'])
    all_match &= compare_tensors("count_ids", count_ids_cpp, reference['decompose/count_ids'])
    all_match &= compare_tensors("table_flag_ids", table_flag_ids_cpp, reference['decompose/table_flag_ids'])

    return all_match


def test_embeddings(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu'
) -> bool:
    """Test embedding layer."""
    print("\n" + "=" * 80)
    print("Testing Embeddings")
    print("=" * 80)

    # Get inputs
    obs_sequence = reference['input/obs_sequence'].to(device)
    act_kind_ids = reference['decompose/act_kind_ids'].to(device)
    count_ids = reference['decompose/count_ids'].to(device)
    table_flag_ids = reference['decompose/table_flag_ids'].to(device)
    agent_types = reference['input/agent_types'].to(device)
    positions = reference['input/positions'].to(device)

    batch_size = obs_sequence.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    embeddings_cpp = lb.test_embeddings(
        obs_sequence,
        act_kind_ids,
        count_ids,
        table_flag_ids,
        agent_types,
        positions,
        batched_weights,
        policy_indices
    )

    # Compare outputs
    all_match = True
    # Test obs_encoder intermediate outputs first
    for key in ['obs_linear', 'obs_layernorm', 'obs_embed']:
        all_match &= compare_tensors(key, embeddings_cpp[key], reference[f'embeddings/{key}'])

    # Then test other embeddings
    for key in ['act_kind_embed', 'count_embed', 'table_flag_embed',
                'action_embed', 'agent_embed', 'position_embed']:
        all_match &= compare_tensors(key, embeddings_cpp[key], reference[f'embeddings/{key}'])

    return all_match


def test_gating(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu'
) -> bool:
    """Test gating layer."""
    print("\n" + "=" * 80)
    print("Testing Gating")
    print("=" * 80)

    # Get inputs from embeddings
    obs_embed = reference['embeddings/obs_embed'].to(device)
    action_embed = reference['embeddings/action_embed'].to(device)
    agent_embed = reference['embeddings/agent_embed'].to(device)
    position_embed = reference['embeddings/position_embed'].to(device)

    batch_size = obs_embed.size(0)
    policy_indices = torch.zeros(batch_size, dtype=torch.long, device=device)

    # Call C++ function
    gating_cpp = lb.test_gating(
        obs_embed,
        action_embed,
        agent_embed,
        position_embed,
        batched_weights,
        policy_indices
    )

    # Compare outputs
    all_match = True
    for key in ['g_obs', 'g_action', 'g_agent', 'g_position']:
        all_match &= compare_tensors(key, gating_cpp[key], reference[f'gating/{key}'])

    return all_match


def test_fusion(
    reference: Dict[str, torch.Tensor],
    device: str = 'cpu',
    hidden_dim: int = 256
) -> bool:
    """Test fusion layer."""
    print("\n" + "=" * 80)
    print("Testing Fusion")
    print("=" * 80)

    # Get inputs
    g_obs = reference['gating/g_obs'].to(device)
    g_action = reference['gating/g_action'].to(device)
    g_agent = reference['gating/g_agent'].to(device)
    g_position = reference['gating/g_position'].to(device)
    obs_embed = reference['embeddings/obs_embed'].to(device)
    action_embed = reference['embeddings/action_embed'].to(device)
    agent_embed = reference['embeddings/agent_embed'].to(device)
    position_embed = reference['embeddings/position_embed'].to(device)

    # Call C++ function
    fusion_cpp = lb.test_fusion(
        g_obs, g_action, g_agent, g_position,
        obs_embed, action_embed, agent_embed, position_embed,
        hidden_dim
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("fused_raw", fusion_cpp['fused_raw'], reference['fusion/fused_raw'])
    all_match &= compare_tensors("combined", fusion_cpp['combined'], reference['fusion/combined'])

    return all_match


def test_transformer_layers(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    num_layers: int = 2,
    num_heads: int = 4,
    num_experts: int = 8,
    top_k: int = 2,
    hidden_dim: int = 256,
    device: str = 'cpu'
) -> bool:
    """Test all transformer layers (attention + MoE)."""
    print("\n" + "=" * 80)
    print("Testing Transformer Layers")
    print("=" * 80)

    all_match = True

    # Start with fusion output
    x_cpp = reference['fusion/combined'].to(device)

    batch_size = x_cpp.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    for layer_idx in range(num_layers):
        print(f"\n--- Layer {layer_idx} ---")

        # Test attention
        print(f"\nAttention Layer {layer_idx}:")
        attn_cpp = lb.test_attention_layer(
            x_cpp,
            batched_weights,
            policy_indices,
            padding_mask,
            layer_idx,
            num_heads,
            hidden_dim
        )

        all_match &= compare_tensors(
            f"layer_{layer_idx}/attn_output",
            attn_cpp['attn_output'],
            reference[f'transformer/layer_{layer_idx}/attn_output']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/post_attn",
            attn_cpp['post_attn'],
            reference[f'transformer/layer_{layer_idx}/post_attn']
        )

        # Use post_attn output for MoE input
        x_cpp = attn_cpp['post_attn']

        # Staged MoE routing and sorting diagnostics before GEMMs
        try:
            rs = lb.test_moe_routing_sort(
                x_cpp,
                batched_weights,
                policy_indices,
                layer_idx,
                num_experts,
                top_k,
            )

            all_match &= compare_tensors(
                f"layer_{layer_idx}/moe_gate_logits",
                rs['gate_logits'],
                reference[f'transformer/layer_{layer_idx}/moe_gate_logits']
            )
            all_match &= compare_tensors(
                f"layer_{layer_idx}/moe_topk_indices",
                rs['topk_indices'],
                reference[f'transformer/layer_{layer_idx}/moe_topk_indices']
            )
            all_match &= compare_tensors(
                f"layer_{layer_idx}/moe_topk_scores",
                rs['topk_weights'],
                reference[f'transformer/layer_{layer_idx}/moe_topk_scores']
            )

            # Compare staged sorted tensors if present in reference
            ref_sorted_experts_key = f'transformer/layer_{layer_idx}/moe_sorted_expert_indices'
            ref_sorted_tokens_key = f'transformer/layer_{layer_idx}/moe_sorted_token_indices'
            ref_sorted_policies_key = f'transformer/layer_{layer_idx}/moe_sorted_policy_indices'
            ref_sorted_weights_key = f'transformer/layer_{layer_idx}/moe_sorted_routing_weights'

            if ref_sorted_experts_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_expert_indices",
                    rs['sorted_expert_indices'],
                    reference[ref_sorted_experts_key]
                )
            if ref_sorted_tokens_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_token_indices",
                    rs['sorted_token_indices'],
                    reference[ref_sorted_tokens_key]
                )
            if ref_sorted_policies_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_policy_indices",
                    rs['sorted_policy_indices'],
                    reference[ref_sorted_policies_key]
                )
            if ref_sorted_weights_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_routing_weights",
                    rs['sorted_routing_weights'],
                    reference[ref_sorted_weights_key]
                )

            grp = lb.test_moe_group_ranges(rs['sorted_expert_indices'], rs['sorted_policy_indices'])
            total_routes = int(rs['sorted_expert_indices'].numel())
            grp_sum = int(grp[:, 1].sum().item()) if grp.numel() > 0 else 0
            if grp_sum != total_routes:
                print(f"[WARN] layer_{layer_idx}: group counts sum {grp_sum} != total routes {total_routes}")
        except Exception as e:
            print(f"[WARN] Staged MoE routing/sorting check failed at layer {layer_idx}: {e}")

        # Test MoE
        print(f"\nMoE Layer {layer_idx}:")
        moe_cpp = lb.test_moe_layer(
            x_cpp,
            batched_weights,
            policy_indices,
            layer_idx,
            num_experts,
            top_k,
            hidden_dim
        )

        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_gate_logits",
            moe_cpp['gate_logits'],
            reference[f'transformer/layer_{layer_idx}/moe_gate_logits']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_topk_indices",
            moe_cpp['topk_indices'],
            reference[f'transformer/layer_{layer_idx}/moe_topk_indices']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_topk_scores",
            moe_cpp['topk_scores'],
            reference[f'transformer/layer_{layer_idx}/moe_topk_scores']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_output",
            moe_cpp['moe_output'],
            reference[f'transformer/layer_{layer_idx}/moe_output']
        )

        # Residual + LayerNorm for next layer (use per-policy LN params)
        residual2 = x_cpp + moe_cpp['moe_output']

        # Gather per-sample gamma/beta for norm2
        ln_gamma = batched_weights[f'transformer.layers.{layer_idx}.norm2.weight'].to(device)
        ln_beta = batched_weights[f'transformer.layers.{layer_idx}.norm2.bias'].to(device)
        # ln_gamma/beta shape: [W, H] -> select per policy -> [B, H]
        gamma_sel = ln_gamma.index_select(0, policy_indices)
        beta_sel = ln_beta.index_select(0, policy_indices)
        # Compute LN manually for [B, T, H]
        eps = 1e-5
        mean = residual2.mean(dim=-1, keepdim=True)
        var = residual2.var(dim=-1, unbiased=False, keepdim=True)
        inv_std = torch.rsqrt(var + eps)
        normed = (residual2 - mean) * inv_std
        # Broadcast gamma/beta to [B, T, H]
        x_cpp = normed * gamma_sel.unsqueeze(1) + beta_sel.unsqueeze(1)

    # Test final norm (uses reference since we're chaining layers)
    transformer_output_ref = reference['transformer/final_output'].to(device)

    # For now, just verify we can proceed to heads
    print("\nFinal transformer output ready for heads")

    return all_match


def test_heads(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    num_experts: int = 8,
    device: str = 'cpu'
) -> bool:
    """Test head layers."""
    print("\n" + "=" * 80)
    print("Testing Heads")
    print("=" * 80)

    # Get transformer output
    transformer_output = reference['transformer/final_output'].to(device)

    batch_size = transformer_output.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    heads_cpp = lb.test_heads(
        transformer_output,
        batched_weights,
        policy_indices,
        num_experts
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("action_heads_stacked", heads_cpp['action_heads_stacked'], reference['heads/action_heads_stacked'])
    all_match &= compare_tensors("opp_heads_stacked", heads_cpp['opp_heads_stacked'], reference['heads/opp_heads_stacked'])
    all_match &= compare_tensors("reward_heads_stacked", heads_cpp['reward_heads_stacked'], reference['heads/reward_heads_stacked'])
    all_match &= compare_tensors("win_heads_stacked", heads_cpp['win_heads_stacked'], reference['heads/win_heads_stacked'])

    return all_match


def main():
    parser = argparse.ArgumentParser(description='Test C++ layers against PyTorch reference')
    parser.add_argument('reference', type=str, help='Path to reference outputs pickle file')
    parser.add_argument('checkpoint', type=str, help='Path to checkpoint')
    parser.add_argument('--checkpoint2', type=str, default=None, help='Optional second checkpoint for multi-policy test')
    parser.add_argument('--agent-key', type=str, default='self', help='Agent key in checkpoint')
    parser.add_argument('--agent-key2', type=str, default='self', help='Agent key in second checkpoint')
    parser.add_argument('--device', type=str, default='cpu', help='Device to use (cpu or cuda)')

    args = parser.parse_args()

    print("=" * 80)
    print("C++ Layer Testing Framework")
    print("=" * 80)
    print(f"Reference: {args.reference}")
    print(f"Checkpoint: {args.checkpoint}")
    print(f"second Checkpoint: {args.checkpoint2}")
    print(f"Device: {args.device}")
    print()

    # Load reference outputs
    print("Loading reference outputs...")
    reference = load_reference(Path(args.reference))
    print(f"Loaded {len(reference)} tensors")

    # Load checkpoint weights
    print("Loading checkpoint weights...")
    state_dict = load_checkpoint_weights(Path(args.checkpoint), args.agent_key)
    state_dict2 = None
    if args.checkpoint2:
        state_dict2 = load_checkpoint_weights(Path(args.checkpoint2), args.agent_key2)
        print(f"Loaded A: {len(state_dict)} tensors; B: {len(state_dict2)} tensors")
    else:
        print(f"Loaded {len(state_dict)} weight tensors")

    # Pad model weights for CUDA alignment
    PAD_OBS_TO = 16
    print(f"Padding model weights for CUDA alignment (obs_dim -> {PAD_OBS_TO})...")
    state_dict = pad_model_weights(state_dict, pad_obs_to=PAD_OBS_TO)
    if state_dict2 is not None:
        state_dict2 = pad_model_weights(state_dict2, pad_obs_to=PAD_OBS_TO)

    # Prepare batched weights for C++ (includes MoE expert weight stacking)
    print("Preparing batched weights...")
    batched_weights = prepare_batched_weights(
        state_dict,
        num_layers=2,
        num_experts=8,
        device=args.device,
        state_dict2=state_dict2,
    )
    print(f"Prepared {len(batched_weights)} batched weights")

    # Diagnostic: Check devices of all tensors
    print("\nDiagnostic: Checking tensor devices...")
    cpu_tensors = []
    cuda_tensors = []
    for key, value in batched_weights.items():
        if value.device.type == 'cpu':
            cpu_tensors.append(key)
        else:
            cuda_tensors.append(key)

    if cpu_tensors:
        print(f"WARNING: Found {len(cpu_tensors)} tensors on CPU:")
        for key in cpu_tensors[:10]:  # Show first 10
            print(f"  - {key}")
        if len(cpu_tensors) > 10:
            print(f"  ... and {len(cpu_tensors) - 10} more")
    else:
        print(f"All {len(batched_weights)} tensors are on {args.device}")

    # Run tests
    results = {}

    results['action_decomposition'] = test_action_decomposition(reference, batched_weights, args.device)
    results['embeddings'] = test_embeddings(reference, batched_weights, args.device)
    results['gating'] = test_gating(reference, batched_weights, args.device)
    results['fusion'] = test_fusion(reference, args.device)
    results['transformer'] = test_transformer_layers(reference, batched_weights, device=args.device)
    results['heads'] = test_heads(reference, batched_weights, device=args.device)

    # Summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)

    for test_name, passed in results.items():
        status = "PASS" if passed else "FAIL"
        print(f"{test_name:30s}: {status}")

    all_passed = all(results.values())
    print()
    if all_passed:
        print("All tests PASSED!")
        return 0
    else:
        print("Some tests FAILED!")
        return 1


if __name__ == '__main__':
    exit(main())
