"""
Test C++ layer implementations against PyTorch reference outputs.

This script loads reference outputs generated by generate_pytorch_reference.py
and compares them against C++ layer-by-layer implementations.
"""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path
from typing import Dict, Optional, Tuple

import torch
import numpy as np

from src.misc import lb
from src.tests import test_utils as tu


def load_reference(path: Path) -> Dict[str, torch.Tensor]:
    """Load reference outputs from pickle file."""
    with open(path, 'rb') as f:
        return pickle.load(f)


def load_checkpoint_weights(checkpoint_path: Path) -> Dict[str, torch.Tensor]:
    """Thin wrapper to shared loader in test_utils."""
    return tu.load_checkpoint_weights(Path(checkpoint_path))


def pad_model_weights(model_state_dict: Dict[str, torch.Tensor], pad_obs_to: int = 16) -> Dict[str, torch.Tensor]:
    """Delegate to shared pad function in test_utils (in-place)."""
    return tu.pad_model_weights(model_state_dict, pad_obs_to=pad_obs_to)


def prepare_batched_weights(
    state_dict: Optional[Dict[str, torch.Tensor]],
    num_layers: int = 2,
    num_experts: int = 8,
    device: str = 'cpu',
    state_dict2: Optional[Dict[str, torch.Tensor]] = None,
) -> Dict[str, torch.Tensor]:
    """Prepare batched weights using shared utils; supports two-policy stacking.

    Single-policy path delegates to ``test_utils.prepare_batched_weights``.
    Two-policy path keeps local batching then pointer/buffer creation.
    """
    print(f"Pre-stacking MoE expert weights ({num_layers} layers, {num_experts} experts)...")
    if state_dict2 is None:
        return tu.prepare_batched_weights(
            state_dict=state_dict, num_layers=num_layers, num_experts=num_experts, device=device, to_fp16=True
        )

    # Two-policy: prestack individually then stack across policies
    sd1 = lb.prestack_moe_expert_weights(dict(state_dict), num_layers, num_experts)
    sd2 = lb.prestack_moe_expert_weights(dict(state_dict2), num_layers, num_experts)
    batched = lb.batch_state_dicts([sd1, sd2])
    for k in list(batched.keys()):
        batched[k] = batched[k].to(device)

    print("Creating MoE weight pointers...")
    batched_with_ptrs = lb.create_moe_weight_pointers(batched, num_layers, num_experts)
    batched_final = lb.add_fixed_buffers(batched_with_ptrs, device)
    return batched_final


def compare_tensors(
    name: str,
    cpp_output: torch.Tensor,
    pytorch_output: torch.Tensor,
    rtol: float = 1e-3,
    atol: float = 1e-4,
) -> bool:
    """Delegate to shared tensor comparison utility."""
    return tu.compare_tensors(name, cpp_output, pytorch_output, rtol=rtol, atol=atol, verbose=True)


def test_action_decomposition(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu'
) -> Tuple[bool, Dict[str, torch.Tensor]]:
    """Test action decomposition layer. Returns (all_match, outputs_dict)."""

    # Get inputs from reference
    action_sequence = reference['input/action_sequence'].to(device)
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    # Policy indices (single policy, index 0)
    batch_size = action_sequence.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    act_kind_ids_cpp, count_ids_cpp, table_flag_ids_cpp = lb.action_decomposition(
        action_sequence,
        batched_weights,
        policy_indices,
        padding_mask,
        count_pad=4,
        tflag_pad=3
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("act_kind_ids", act_kind_ids_cpp, reference['decompose/act_kind_ids'])
    all_match &= compare_tensors("count_ids", count_ids_cpp, reference['decompose/count_ids'])
    all_match &= compare_tensors("table_flag_ids", table_flag_ids_cpp, reference['decompose/table_flag_ids'])

    outputs = {
        'act_kind_ids': act_kind_ids_cpp,
        'count_ids': count_ids_cpp,
        'table_flag_ids': table_flag_ids_cpp,
    }
    return all_match, outputs


def test_embeddings(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu',
    act_kind_ids_override: Optional[torch.Tensor] = None,
    count_ids_override: Optional[torch.Tensor] = None,
    table_flag_ids_override: Optional[torch.Tensor] = None,
) -> Tuple[bool, Dict[str, torch.Tensor]]:
    """Test embedding layer. Returns (all_match, embeddings_cpp_dict)."""

    # Get inputs and convert to FP16 for C++ kernels
    obs_sequence = reference['input/obs_sequence'].to(device, dtype=torch.float16)
    action_sequence = reference['input/action_sequence'].to(device)
    agent_types = reference['input/agent_types'].to(device)
    positions = reference['input/positions'].to(device)

    batch_size = obs_sequence.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Get padding mask if available
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    # Keep decomposed IDs for comparison (not used by C++ anymore)
    act_kind_ids = (act_kind_ids_override if act_kind_ids_override is not None
                    else reference['decompose/act_kind_ids']).to(device)
    count_ids = (count_ids_override if count_ids_override is not None
                 else reference['decompose/count_ids']).to(device)
    table_flag_ids = (table_flag_ids_override if table_flag_ids_override is not None
                      else reference['decompose/table_flag_ids']).to(device)
    embeddings_cpp = lb.compute_embeddings(
        obs_sequence,
        action_sequence,
        agent_types,
        positions,
        batched_weights,
        policy_indices,
        padding_mask,
        4,  # count_pad
        3   # tflag_pad
    )

    # Compare outputs
    all_match = True
    # Compare only the keys that C++ actually returns (final embeddings only)
    for key in ['obs_embed', 'action_embed', 'agent_embed', 'position_embed']:
        if key in embeddings_cpp and f'embeddings/{key}' in reference:
            all_match &= compare_tensors(key, embeddings_cpp[key], reference[f'embeddings/{key}'])
        else:
            print(f"⚠️  Skipping {key}: not found in C++ output or reference")
            all_match = False

    return all_match, embeddings_cpp


def test_gating(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu',
    obs_embed_override: Optional[torch.Tensor] = None,
    action_embed_override: Optional[torch.Tensor] = None,
    agent_embed_override: Optional[torch.Tensor] = None,
    position_embed_override: Optional[torch.Tensor] = None,
) -> Tuple[bool, Dict[str, torch.Tensor]]:
    """Test gating layer. Returns (all_match, gating_cpp_dict)."""

    # Get inputs from embeddings and convert to FP16 for C++ kernels
    obs_embed = (obs_embed_override if obs_embed_override is not None
                 else reference['embeddings/obs_embed']).to(device, dtype=torch.float16)
    action_embed = (action_embed_override if action_embed_override is not None
                    else reference['embeddings/action_embed']).to(device, dtype=torch.float16)
    agent_embed = (agent_embed_override if agent_embed_override is not None
                   else reference['embeddings/agent_embed']).to(device, dtype=torch.float16)
    position_embed = (position_embed_override if position_embed_override is not None
                      else reference['embeddings/position_embed']).to(device, dtype=torch.float16)

    batch_size = obs_embed.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    gating_cpp = lb.gating(
        obs_embed,
        action_embed,
        agent_embed,
        position_embed,
        batched_weights,
        policy_indices
    )

    # Compare outputs
    all_match = True
    for key in ['g_obs', 'g_action', 'g_agent', 'g_position']:
        all_match &= compare_tensors(key, gating_cpp[key], reference[f'gating/{key}'])

    return all_match, gating_cpp


def test_fusion(
    reference: Dict[str, torch.Tensor],
    device: str = 'cpu',
    hidden_dim: int = 256,
    g_obs_override: Optional[torch.Tensor] = None,
    g_action_override: Optional[torch.Tensor] = None,
    g_agent_override: Optional[torch.Tensor] = None,
    g_position_override: Optional[torch.Tensor] = None,
    obs_embed_override: Optional[torch.Tensor] = None,
    action_embed_override: Optional[torch.Tensor] = None,
    agent_embed_override: Optional[torch.Tensor] = None,
    position_embed_override: Optional[torch.Tensor] = None,
) -> tuple[bool, dict]:
    """Test fusion layer. Returns (all_match, fusion_outputs_dict)."""

    # Get inputs (override if provided)
    g_obs = (g_obs_override if g_obs_override is not None else reference['gating/g_obs']).to(device)
    g_action = (g_action_override if g_action_override is not None else reference['gating/g_action']).to(device)
    g_agent = (g_agent_override if g_agent_override is not None else reference['gating/g_agent']).to(device)
    g_position = (g_position_override if g_position_override is not None else reference['gating/g_position']).to(device)

    obs_embed = (obs_embed_override if obs_embed_override is not None else reference['embeddings/obs_embed']).to(device)
    action_embed = (action_embed_override if action_embed_override is not None else reference['embeddings/action_embed']).to(device)
    agent_embed = (agent_embed_override if agent_embed_override is not None else reference['embeddings/agent_embed']).to(device)
    position_embed = (position_embed_override if position_embed_override is not None else reference['embeddings/position_embed']).to(device)

    # Call C++ function
    fusion_cpp = lb.fuse_embeddings(
        g_obs, g_action, g_agent, g_position,
        obs_embed, action_embed, agent_embed, position_embed,
        hidden_dim
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("fused_raw", fusion_cpp['fused_raw'], reference['fusion/fused_raw'])
    all_match &= compare_tensors("combined", fusion_cpp['combined'], reference['fusion/combined'])

    return all_match, fusion_cpp


def test_transformer_layers(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    num_layers: int = 2,
    num_heads: int = 4,
    num_experts: int = 8,
    top_k: int = 2,
    hidden_dim: int = 256,
    device: str = 'cpu',
    fusion_combined: torch.Tensor = None
) -> tuple[bool, torch.Tensor]:
    """Test all transformer layers (attention + MoE). Returns (all_match, final_output)."""

    all_match = True

    # Start with fusion output (either passed in or from reference), convert to FP16 for C++ kernels
    if fusion_combined is not None:
        x_cpp = fusion_combined.to(device, dtype=torch.float16)
    else:
        x_cpp = reference['fusion/combined'].to(device, dtype=torch.float16)

    batch_size = x_cpp.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    for layer_idx in range(num_layers):
        print(f"\n--- Layer {layer_idx} ---")

        # DEBUG: Check weight dtypes for this layer
        layer_prefix = f"transformer.layers.{layer_idx}"
        weight_keys = [
            f"{layer_prefix}.self_attn.in_proj_weight",
            f"{layer_prefix}.moe.experts.w1_ptrs",
            f"{layer_prefix}.moe.experts.b1_ptrs",
        ]
        print(f"DEBUG: Weight dtypes for layer {layer_idx}:")
        for key in weight_keys:
            if key in batched_weights:
                print(f"  {key}: dtype={batched_weights[key].dtype}, shape={batched_weights[key].shape}")

        # Call transformer_layer (combines attention + MoE + residuals + norms)
        print(f"  x_cpp: shape={x_cpp.shape}, dtype={x_cpp.dtype}, device={x_cpp.device}")
        print(f"  policy_indices: shape={policy_indices.shape}, dtype={policy_indices.dtype}")
        print(f"  Calling lb.transformer_layer...")
        try:
            x_next, gate_logits, topk_indices, topk_scores = lb.transformer_layer(
                x_cpp,
                policy_indices,
                batched_weights,
                layer_idx,
                num_heads,
                hidden_dim,
                top_k,
                8,  # num_experts
                1   # num_policies
            )
            print(f"  Success! x_next: shape={x_next.shape}, dtype={x_next.dtype}")
        except Exception as e:
            print(f"  EXCEPTION: {type(e).__name__}: {e}")
            raise

        # Compare MoE outputs
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_gate_logits",
            gate_logits,
            reference[f'transformer/layer_{layer_idx}/moe_gate_logits']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_topk_indices",
            topk_indices,
            reference[f'transformer/layer_{layer_idx}/moe_topk_indices']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_topk_scores",
            topk_scores,
            reference[f'transformer/layer_{layer_idx}/moe_topk_scores']
        )

        # Update x for next layer
        x_cpp = x_next

    # Test final norm (uses reference since we're chaining layers)
    transformer_output_ref = reference['transformer/final_output'].to(device)

    # For now, just verify we can proceed to heads
    print("\nFinal transformer output ready for heads")

    return all_match, x_cpp


def test_heads(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    num_experts: int = 8,
    device: str = 'cpu',
    transformer_output: torch.Tensor = None
) -> bool:
    """Test head layers."""

    # Get transformer output (either passed in or from reference), convert to FP16 for C++ kernels
    if transformer_output is not None:
        transformer_output = transformer_output.to(device, dtype=torch.float16)
    else:
        transformer_output = reference['transformer/final_output'].to(device, dtype=torch.float16)

    batch_size = transformer_output.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    heads_cpp = lb.compute_heads(
        transformer_output,
        batched_weights,
        policy_indices,
        num_experts
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("action_heads_stacked", heads_cpp['action_heads_stacked'], reference['heads/action_heads_stacked'])
    all_match &= compare_tensors("opp_heads_stacked", heads_cpp['opp_heads_stacked'], reference['heads/opp_heads_stacked'])
    all_match &= compare_tensors("reward_heads_stacked", heads_cpp['reward_heads_stacked'], reference['heads/reward_heads_stacked'])
    all_match &= compare_tensors("win_heads_stacked", heads_cpp['win_heads_stacked'], reference['heads/win_heads_stacked'])

    return all_match


def main():
    parser = argparse.ArgumentParser(description='Test C++ layers against PyTorch reference')
    parser.add_argument('reference', type=str, help='Path to reference outputs pickle file')
    parser.add_argument('checkpoint', type=str, help='Path to checkpoint')
    parser.add_argument('--checkpoint2', type=str, default=None, help='Optional second checkpoint for multi-policy test')
    parser.add_argument('--device', type=str, default='cuda', help='Device to use (cpu or cuda)')
    parser.add_argument('--chain-outputs', action='store_true',
                        help='Chain outputs through layers instead of using reference inputs for each layer (shows end-to-end error accumulation)')

    args = parser.parse_args()

    # Load reference outputs
    reference = load_reference(Path(args.reference))

    # Load checkpoint weights
    print("Loading checkpoint weights...")
    state_dict = load_checkpoint_weights(Path(args.checkpoint))
    state_dict2 = None
    if args.checkpoint2:
        state_dict2 = load_checkpoint_weights(Path(args.checkpoint2))
        print(f"Loaded A: {len(state_dict)} tensors; B: {len(state_dict2)} tensors")
    else:
        print(f"Loaded {len(state_dict)} weight tensors")

    # Prepare batched weights for C++ (includes MoE expert weight stacking)
    print("Preparing batched weights...")
    batched_weights = prepare_batched_weights(
        state_dict,
        num_layers=2,
        num_experts=8,
        device=args.device,
        state_dict2=state_dict2,
    )
    print(f"Prepared {len(batched_weights)} batched weights")

    # Diagnostic: Check devices of all tensors
    print("\nDiagnostic: Checking tensor devices...")
    cpu_tensors = []
    cuda_tensors = []
    for key, value in batched_weights.items():
        if value.device.type == 'cpu':
            cpu_tensors.append(key)
        else:
            cuda_tensors.append(key)

    if cpu_tensors:
        print(f"WARNING: Found {len(cpu_tensors)} tensors on CPU:")
        for key in cpu_tensors[:10]:  # Show first 10
            print(f"  - {key}")
        if len(cpu_tensors) > 10:
            print(f"  ... and {len(cpu_tensors) - 10} more")
    else:
        print(f"All {len(batched_weights)} tensors are on {args.device}")

    # Enable MoE workspace cache for transformer layers (required for CUTLASS kernels)
    batch_size = reference['input/obs_sequence'].size(0)
    seq_len = reference['input/obs_sequence'].size(1)
    print(f"\nEnabling MoE workspace cache (batch={batch_size}, seq_len={seq_len})...")
    lb.enable_forward_moe_workspace_cache(
        num_layers=2,
        max_batch_size=batch_size,
        max_seq_length=seq_len,
        hidden_dim=256,
        top_k=2
    )

    # Run tests
    results = {}

    # Always run action decomposition first (needed either way)
    ad_pass, ad_outputs = test_action_decomposition(reference, batched_weights, args.device)
    results['action_decomposition'] = ad_pass

    if args.chain_outputs:
        # Use C++ outputs to chain through embeddings -> gating -> fusion -> transformer -> heads
        emb_pass, emb_outputs = test_embeddings(
            reference, batched_weights, args.device,
            act_kind_ids_override=ad_outputs['act_kind_ids'],
            count_ids_override=ad_outputs['count_ids'],
            table_flag_ids_override=ad_outputs['table_flag_ids'],
        )
        results['embeddings'] = emb_pass

        gating_pass, gating_outputs = test_gating(
            reference, batched_weights, args.device,
            obs_embed_override=emb_outputs['obs_embed'],
            action_embed_override=emb_outputs['action_embed'],
            agent_embed_override=emb_outputs['agent_embed'],
            position_embed_override=emb_outputs['position_embed'],
        )
        results['gating'] = gating_pass

        fusion_pass, fusion_outputs = test_fusion(
            reference, args.device,
            g_obs_override=gating_outputs['g_obs'],
            g_action_override=gating_outputs['g_action'],
            g_agent_override=gating_outputs['g_agent'],
            g_position_override=gating_outputs['g_position'],
            obs_embed_override=emb_outputs['obs_embed'],
            action_embed_override=emb_outputs['action_embed'],
            agent_embed_override=emb_outputs['agent_embed'],
            position_embed_override=emb_outputs['position_embed'],
        )
        results['fusion'] = fusion_pass

        transformer_pass, transformer_output = test_transformer_layers(
            reference, batched_weights, device=args.device,
            fusion_combined=fusion_outputs['combined']
        )
        results['transformer'] = transformer_pass

        results['heads'] = test_heads(
            reference, batched_weights, device=args.device,
            transformer_output=transformer_output
        )
    else:
        # Use reference inputs for each layer (default)
        emb_pass, _ = test_embeddings(reference, batched_weights, args.device)
        results['embeddings'] = emb_pass

        gating_pass, _ = test_gating(reference, batched_weights, args.device)
        results['gating'] = gating_pass

        fusion_pass, _ = test_fusion(reference, args.device)
        results['fusion'] = fusion_pass

        transformer_pass, _ = test_transformer_layers(reference, batched_weights, device=args.device)
        results['transformer'] = transformer_pass

        results['heads'] = test_heads(reference, batched_weights, device=args.device)

    # Disable MoE workspace cache after tests
    print("\nDisabling MoE workspace cache...")
    lb.disable_forward_moe_workspace_cache()

    # Return 0 if all passed, 1 if any failed
    return 0 if all(results.values()) else 1


if __name__ == '__main__':
    exit(main())
