"""
Test C++ layer implementations against PyTorch reference outputs.

This script loads reference outputs generated by generate_pytorch_reference.py
and compares them against C++ layer-by-layer implementations.
"""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path
from typing import Dict, Optional, Tuple

import torch
import numpy as np

from src.misc import lb


def load_reference(path: Path) -> Dict[str, torch.Tensor]:
    """Load reference outputs from pickle file."""
    with open(path, 'rb') as f:
        return pickle.load(f)


def load_checkpoint_weights(checkpoint_path: Path) -> Dict[str, torch.Tensor]:
    """Load model weights from checkpoint."""
    checkpoint = torch.load(checkpoint_path, map_location='cpu')

    if 'model_state_dict' in checkpoint:
        return checkpoint['model_state_dict']
    elif 'policy_nets' in checkpoint:
        # Legacy format: try 'self' key
        if 'self' in checkpoint['policy_nets']:
            return checkpoint['policy_nets']['self']
        # Otherwise return first policy
        first_key = next(iter(checkpoint['policy_nets']))
        return checkpoint['policy_nets'][first_key]
    else:
        raise ValueError(f"Could not find model state dict in checkpoint (keys: {list(checkpoint.keys())})")


def pad_model_weights(model_state_dict: Dict[str, torch.Tensor], pad_obs_to: int = 16) -> Dict[str, torch.Tensor]:
    """
    Pad observation encoder weights for CUDA alignment.

    Args:
        model_state_dict: Model state dictionary
        pad_obs_to: Target dimension for padding (default 16)

    Returns:
        Modified state dict with padded weights
    """
    # Pad obs_encoder.0.weight from [hidden_dim, obs_dim] to [hidden_dim, pad_obs_to]
    obs_linear_weight_key = "obs_encoder.0.weight"
    if obs_linear_weight_key in model_state_dict:
        weight = model_state_dict[obs_linear_weight_key]
        hidden_dim, obs_dim = weight.shape

        if obs_dim < pad_obs_to:
            # Pad with zeros
            padding = torch.zeros(hidden_dim, pad_obs_to - obs_dim, dtype=weight.dtype, device=weight.device)
            padded_weight = torch.cat([weight, padding], dim=1)
            model_state_dict[obs_linear_weight_key] = padded_weight
            print(f"Padded {obs_linear_weight_key} from [{hidden_dim}, {obs_dim}] to [{hidden_dim}, {pad_obs_to}]")

    return model_state_dict


def prepare_batched_weights(
    state_dict: Optional[Dict[str, torch.Tensor]],
    num_layers: int = 2,
    num_experts: int = 8,
    device: str = 'cpu',
    state_dict2: Optional[Dict[str, torch.Tensor]] = None,
) -> Dict[str, torch.Tensor]:
    """
    Prepare batched weights for C++ testing.

    For single-policy testing, we add a batch dimension to all weights.
    Also pre-stacks MoE expert weights and creates pointer tensors.
    """
    # First, prestack MoE expert weights (must be done before adding batch dim)
    print(f"Pre-stacking MoE expert weights ({num_layers} layers, {num_experts} experts)...")
    if state_dict2 is None:
        state_dict_stacked = lb.prestack_moe_expert_weights(state_dict, num_layers, num_experts)
        batched: Dict[str, torch.Tensor] = {}
        for key, value in state_dict_stacked.items():
            # Add batch dimension [1, ...] and move to device
            t = value.unsqueeze(0).to(device)
            batched[key] = t
    else:
        # Two-policy: prestack individually then stack across policies
        sd1 = lb.prestack_moe_expert_weights(dict(state_dict), num_layers, num_experts)
        sd2 = lb.prestack_moe_expert_weights(dict(state_dict2), num_layers, num_experts)
        batched = lb.batch_state_dicts([sd1, sd2])
        for k in list(batched.keys()):
            batched[k] = batched[k].to(device)

    # If using CUDA, convert floating-point weights to FP16 before creating
    # MoE pointer tensors so that GPU kernels (which expect Half) match dtype.
    if device.startswith('cuda'):
        for key, tensor in list(batched.items()):
            if tensor.is_floating_point():
                batched[key] = tensor.to(torch.float16).contiguous()

    # Create MoE weight pointers (must be done after moving to device)
    print("Creating MoE weight pointers...")
    batched_with_ptrs = lb.create_moe_weight_pointers(batched, num_layers, num_experts)

    # Add fixed buffers (action decomposition LUTs)
    batched_final = lb.add_fixed_buffers(batched_with_ptrs, device)

    return batched_final


def compare_tensors(
    name: str,
    cpp_output: torch.Tensor,
    pytorch_output: torch.Tensor,
    rtol: float = 1e-3,
    atol: float = 1e-4
) -> bool:
    """
    Compare two tensors and report statistics.
    Only prints output if there's a failure.

    Returns:
        True if tensors match within tolerance, False otherwise
    """
    # Move to CPU and convert to float32 for comparison
    cpp_np = cpp_output.detach().cpu().float().numpy()
    pytorch_np = pytorch_output.detach().cpu().float().numpy()

    # Check shapes
    if cpp_np.shape != pytorch_np.shape:
        print(f"{name}: SHAPE MISMATCH C++={cpp_np.shape} vs PyTorch={pytorch_np.shape}")
        return False

    # Compute errors
    abs_diff = np.abs(cpp_np - pytorch_np)

    max_abs_error = np.max(abs_diff)
    mean_abs_error = np.mean(abs_diff)

    # Check if within tolerance
    matches = np.allclose(cpp_np, pytorch_np, rtol=rtol, atol=atol)

    # Only print if failed
    if not matches:
        mismatch_mask = abs_diff > (atol + rtol * np.abs(pytorch_np))
        mismatch_indices = np.where(mismatch_mask)
        num_mismatches = len(mismatch_indices[0])
        mismatch_pct = 100 * num_mismatches / cpp_np.size
        print(f"{name}: {mismatch_pct:.2f}% mismatch, max_err={max_abs_error:.2e}, mean_err={mean_abs_error:.2e}")

    return matches


def test_action_decomposition(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu'
) -> Tuple[bool, Dict[str, torch.Tensor]]:
    """Test action decomposition layer. Returns (all_match, outputs_dict)."""

    # Get inputs from reference
    action_sequence = reference['input/action_sequence'].to(device)
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    # Policy indices (single policy, index 0)
    batch_size = action_sequence.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    act_kind_ids_cpp, count_ids_cpp, table_flag_ids_cpp = lb.test_action_decomposition(
        action_sequence,
        batched_weights,
        policy_indices,
        padding_mask,
        count_pad=4,
        tflag_pad=3
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("act_kind_ids", act_kind_ids_cpp, reference['decompose/act_kind_ids'])
    all_match &= compare_tensors("count_ids", count_ids_cpp, reference['decompose/count_ids'])
    all_match &= compare_tensors("table_flag_ids", table_flag_ids_cpp, reference['decompose/table_flag_ids'])

    outputs = {
        'act_kind_ids': act_kind_ids_cpp,
        'count_ids': count_ids_cpp,
        'table_flag_ids': table_flag_ids_cpp,
    }
    return all_match, outputs


def test_embeddings(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu',
    act_kind_ids_override: Optional[torch.Tensor] = None,
    count_ids_override: Optional[torch.Tensor] = None,
    table_flag_ids_override: Optional[torch.Tensor] = None,
) -> Tuple[bool, Dict[str, torch.Tensor]]:
    """Test embedding layer. Returns (all_match, embeddings_cpp_dict)."""

    # Get inputs
    obs_sequence = reference['input/obs_sequence'].to(device)
    act_kind_ids = (act_kind_ids_override if act_kind_ids_override is not None
                    else reference['decompose/act_kind_ids']).to(device)
    count_ids = (count_ids_override if count_ids_override is not None
                 else reference['decompose/count_ids']).to(device)
    table_flag_ids = (table_flag_ids_override if table_flag_ids_override is not None
                      else reference['decompose/table_flag_ids']).to(device)
    agent_types = reference['input/agent_types'].to(device)
    positions = reference['input/positions'].to(device)

    batch_size = obs_sequence.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    embeddings_cpp = lb.test_embeddings(
        obs_sequence,
        act_kind_ids,
        count_ids,
        table_flag_ids,
        agent_types,
        positions,
        batched_weights,
        policy_indices
    )

    # Compare outputs
    all_match = True
    # Test obs_encoder intermediate outputs first
    for key in ['obs_linear', 'obs_layernorm', 'obs_embed']:
        all_match &= compare_tensors(key, embeddings_cpp[key], reference[f'embeddings/{key}'])

    # Then test other embeddings
    for key in ['act_kind_embed', 'count_embed', 'table_flag_embed',
                'action_embed', 'agent_embed', 'position_embed']:
        all_match &= compare_tensors(key, embeddings_cpp[key], reference[f'embeddings/{key}'])

    return all_match, embeddings_cpp


def test_gating(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    device: str = 'cpu',
    obs_embed_override: Optional[torch.Tensor] = None,
    action_embed_override: Optional[torch.Tensor] = None,
    agent_embed_override: Optional[torch.Tensor] = None,
    position_embed_override: Optional[torch.Tensor] = None,
) -> Tuple[bool, Dict[str, torch.Tensor]]:
    """Test gating layer. Returns (all_match, gating_cpp_dict)."""

    # Get inputs from embeddings
    obs_embed = (obs_embed_override if obs_embed_override is not None
                 else reference['embeddings/obs_embed']).to(device)
    action_embed = (action_embed_override if action_embed_override is not None
                    else reference['embeddings/action_embed']).to(device)
    agent_embed = (agent_embed_override if agent_embed_override is not None
                   else reference['embeddings/agent_embed']).to(device)
    position_embed = (position_embed_override if position_embed_override is not None
                      else reference['embeddings/position_embed']).to(device)

    batch_size = obs_embed.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    gating_cpp = lb.test_gating(
        obs_embed,
        action_embed,
        agent_embed,
        position_embed,
        batched_weights,
        policy_indices
    )

    # Compare outputs
    all_match = True
    for key in ['g_obs', 'g_action', 'g_agent', 'g_position']:
        all_match &= compare_tensors(key, gating_cpp[key], reference[f'gating/{key}'])

    return all_match, gating_cpp


def test_fusion(
    reference: Dict[str, torch.Tensor],
    device: str = 'cpu',
    hidden_dim: int = 256,
    g_obs_override: Optional[torch.Tensor] = None,
    g_action_override: Optional[torch.Tensor] = None,
    g_agent_override: Optional[torch.Tensor] = None,
    g_position_override: Optional[torch.Tensor] = None,
    obs_embed_override: Optional[torch.Tensor] = None,
    action_embed_override: Optional[torch.Tensor] = None,
    agent_embed_override: Optional[torch.Tensor] = None,
    position_embed_override: Optional[torch.Tensor] = None,
) -> tuple[bool, dict]:
    """Test fusion layer. Returns (all_match, fusion_outputs_dict)."""

    # Get inputs (override if provided)
    g_obs = (g_obs_override if g_obs_override is not None else reference['gating/g_obs']).to(device)
    g_action = (g_action_override if g_action_override is not None else reference['gating/g_action']).to(device)
    g_agent = (g_agent_override if g_agent_override is not None else reference['gating/g_agent']).to(device)
    g_position = (g_position_override if g_position_override is not None else reference['gating/g_position']).to(device)

    obs_embed = (obs_embed_override if obs_embed_override is not None else reference['embeddings/obs_embed']).to(device)
    action_embed = (action_embed_override if action_embed_override is not None else reference['embeddings/action_embed']).to(device)
    agent_embed = (agent_embed_override if agent_embed_override is not None else reference['embeddings/agent_embed']).to(device)
    position_embed = (position_embed_override if position_embed_override is not None else reference['embeddings/position_embed']).to(device)

    # Call C++ function
    fusion_cpp = lb.test_fusion(
        g_obs, g_action, g_agent, g_position,
        obs_embed, action_embed, agent_embed, position_embed,
        hidden_dim
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("fused_raw", fusion_cpp['fused_raw'], reference['fusion/fused_raw'])
    all_match &= compare_tensors("combined", fusion_cpp['combined'], reference['fusion/combined'])

    return all_match, fusion_cpp


def test_transformer_layers(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    num_layers: int = 2,
    num_heads: int = 4,
    num_experts: int = 8,
    top_k: int = 2,
    hidden_dim: int = 256,
    device: str = 'cpu',
    fusion_combined: torch.Tensor = None
) -> tuple[bool, torch.Tensor]:
    """Test all transformer layers (attention + MoE). Returns (all_match, final_output)."""

    all_match = True

    # Start with fusion output (either passed in or from reference)
    if fusion_combined is not None:
        x_cpp = fusion_combined.to(device)
    else:
        x_cpp = reference['fusion/combined'].to(device)

    batch_size = x_cpp.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)
    padding_mask = reference.get('input/padding_mask')
    if padding_mask is not None:
        padding_mask = padding_mask.to(device)

    for layer_idx in range(num_layers):
        print(f"\n--- Layer {layer_idx} ---")

        # Test attention
        print(f"\nAttention Layer {layer_idx}:")
        attn_cpp = lb.test_attention_layer(
            x_cpp,
            batched_weights,
            policy_indices,
            padding_mask,
            layer_idx,
            num_heads,
            hidden_dim
        )

        all_match &= compare_tensors(
            f"layer_{layer_idx}/attn_output",
            attn_cpp['attn_output'],
            reference[f'transformer/layer_{layer_idx}/attn_output']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/post_attn",
            attn_cpp['post_attn'],
            reference[f'transformer/layer_{layer_idx}/post_attn']
        )

        # Use post_attn output for MoE input
        x_cpp = attn_cpp['post_attn']

        # Staged MoE routing and sorting diagnostics before GEMMs
        try:
            rs = lb.test_moe_routing_sort(
                x_cpp,
                batched_weights,
                policy_indices,
                layer_idx,
                num_experts,
                top_k,
            )

            all_match &= compare_tensors(
                f"layer_{layer_idx}/moe_gate_logits",
                rs['gate_logits'],
                reference[f'transformer/layer_{layer_idx}/moe_gate_logits']
            )
            all_match &= compare_tensors(
                f"layer_{layer_idx}/moe_topk_indices",
                rs['topk_indices'],
                reference[f'transformer/layer_{layer_idx}/moe_topk_indices']
            )
            all_match &= compare_tensors(
                f"layer_{layer_idx}/moe_topk_scores",
                rs['topk_weights'],
                reference[f'transformer/layer_{layer_idx}/moe_topk_scores']
            )

            # Compare staged sorted tensors if present in reference
            ref_sorted_experts_key = f'transformer/layer_{layer_idx}/moe_sorted_expert_indices'
            ref_sorted_tokens_key = f'transformer/layer_{layer_idx}/moe_sorted_token_indices'
            ref_sorted_policies_key = f'transformer/layer_{layer_idx}/moe_sorted_policy_indices'
            ref_sorted_weights_key = f'transformer/layer_{layer_idx}/moe_sorted_routing_weights'

            if ref_sorted_experts_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_expert_indices",
                    rs['sorted_expert_indices'],
                    reference[ref_sorted_experts_key]
                )
            if ref_sorted_tokens_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_token_indices",
                    rs['sorted_token_indices'],
                    reference[ref_sorted_tokens_key]
                )
            if ref_sorted_policies_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_policy_indices",
                    rs['sorted_policy_indices'],
                    reference[ref_sorted_policies_key]
                )
            if ref_sorted_weights_key in reference:
                all_match &= compare_tensors(
                    f"layer_{layer_idx}/moe_sorted_routing_weights",
                    rs['sorted_routing_weights'],
                    reference[ref_sorted_weights_key]
                )

            grp = lb.test_moe_group_ranges(rs['sorted_expert_indices'], rs['sorted_policy_indices'])
            total_routes = int(rs['sorted_expert_indices'].numel())
            grp_sum = int(grp[:, 1].sum().item()) if grp.numel() > 0 else 0
            if grp_sum != total_routes:
                print(f"[WARN] layer_{layer_idx}: group counts sum {grp_sum} != total routes {total_routes}")
        except Exception as e:
            print(f"[WARN] Staged MoE routing/sorting check failed at layer {layer_idx}: {e}")

        # Test MoE
        print(f"\nMoE Layer {layer_idx}:")
        moe_cpp = lb.test_moe_layer(
            x_cpp,
            batched_weights,
            policy_indices,
            layer_idx,
            num_experts,
            top_k,
            hidden_dim
        )

        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_gate_logits",
            moe_cpp['gate_logits'],
            reference[f'transformer/layer_{layer_idx}/moe_gate_logits']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_topk_indices",
            moe_cpp['topk_indices'],
            reference[f'transformer/layer_{layer_idx}/moe_topk_indices']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_topk_scores",
            moe_cpp['topk_scores'],
            reference[f'transformer/layer_{layer_idx}/moe_topk_scores']
        )
        all_match &= compare_tensors(
            f"layer_{layer_idx}/moe_output",
            moe_cpp['moe_output'],
            reference[f'transformer/layer_{layer_idx}/moe_output']
        )

        # Residual + LayerNorm for next layer (use per-policy LN params)
        residual2 = x_cpp + moe_cpp['moe_output']

        # Gather per-sample gamma/beta for norm2
        ln_gamma = batched_weights[f'transformer.layers.{layer_idx}.norm2.weight'].to(device)
        ln_beta = batched_weights[f'transformer.layers.{layer_idx}.norm2.bias'].to(device)
        # ln_gamma/beta shape: [W, H] -> select per policy -> [B, H]
        gamma_sel = ln_gamma.index_select(0, policy_indices)
        beta_sel = ln_beta.index_select(0, policy_indices)
        # Compute LN manually for [B, T, H]
        eps = 1e-5
        mean = residual2.mean(dim=-1, keepdim=True)
        var = residual2.var(dim=-1, unbiased=False, keepdim=True)
        inv_std = torch.rsqrt(var + eps)
        normed = (residual2 - mean) * inv_std
        # Broadcast gamma/beta to [B, T, H]
        x_cpp = normed * gamma_sel.unsqueeze(1) + beta_sel.unsqueeze(1)

    # Test final norm (uses reference since we're chaining layers)
    transformer_output_ref = reference['transformer/final_output'].to(device)

    # For now, just verify we can proceed to heads
    print("\nFinal transformer output ready for heads")

    return all_match, x_cpp


def test_heads(
    reference: Dict[str, torch.Tensor],
    batched_weights: Dict[str, torch.Tensor],
    num_experts: int = 8,
    device: str = 'cpu',
    transformer_output: torch.Tensor = None
) -> bool:
    """Test head layers."""

    # Get transformer output (either passed in or from reference)
    if transformer_output is not None:
        transformer_output = transformer_output.to(device)
    else:
        transformer_output = reference['transformer/final_output'].to(device)

    batch_size = transformer_output.size(0)
    policy_indices = reference.get('input/policy_indices', torch.zeros(batch_size, dtype=torch.long)).to(device)

    # Call C++ function
    heads_cpp = lb.test_heads(
        transformer_output,
        batched_weights,
        policy_indices,
        num_experts
    )

    # Compare outputs
    all_match = True
    all_match &= compare_tensors("action_heads_stacked", heads_cpp['action_heads_stacked'], reference['heads/action_heads_stacked'])
    all_match &= compare_tensors("opp_heads_stacked", heads_cpp['opp_heads_stacked'], reference['heads/opp_heads_stacked'])
    all_match &= compare_tensors("reward_heads_stacked", heads_cpp['reward_heads_stacked'], reference['heads/reward_heads_stacked'])
    all_match &= compare_tensors("win_heads_stacked", heads_cpp['win_heads_stacked'], reference['heads/win_heads_stacked'])

    return all_match


def main():
    parser = argparse.ArgumentParser(description='Test C++ layers against PyTorch reference')
    parser.add_argument('reference', type=str, help='Path to reference outputs pickle file')
    parser.add_argument('checkpoint', type=str, help='Path to checkpoint')
    parser.add_argument('--checkpoint2', type=str, default=None, help='Optional second checkpoint for multi-policy test')
    parser.add_argument('--device', type=str, default='cuda', help='Device to use (cpu or cuda)')
    parser.add_argument('--chain-outputs', action='store_true',
                        help='Chain outputs through layers instead of using reference inputs for each layer (shows end-to-end error accumulation)')

    args = parser.parse_args()

    # Load reference outputs
    reference = load_reference(Path(args.reference))

    # Load checkpoint weights
    print("Loading checkpoint weights...")
    state_dict = load_checkpoint_weights(Path(args.checkpoint))
    state_dict2 = None
    if args.checkpoint2:
        state_dict2 = load_checkpoint_weights(Path(args.checkpoint2))
        print(f"Loaded A: {len(state_dict)} tensors; B: {len(state_dict2)} tensors")
    else:
        print(f"Loaded {len(state_dict)} weight tensors")

    # Pad model weights for CUDA alignment
    PAD_OBS_TO = 16
    print(f"Padding model weights for CUDA alignment (obs_dim -> {PAD_OBS_TO})...")
    state_dict = pad_model_weights(state_dict, pad_obs_to=PAD_OBS_TO)
    if state_dict2 is not None:
        state_dict2 = pad_model_weights(state_dict2, pad_obs_to=PAD_OBS_TO)

    # Prepare batched weights for C++ (includes MoE expert weight stacking)
    print("Preparing batched weights...")
    batched_weights = prepare_batched_weights(
        state_dict,
        num_layers=2,
        num_experts=8,
        device=args.device,
        state_dict2=state_dict2,
    )
    print(f"Prepared {len(batched_weights)} batched weights")

    # Diagnostic: Check devices of all tensors
    print("\nDiagnostic: Checking tensor devices...")
    cpu_tensors = []
    cuda_tensors = []
    for key, value in batched_weights.items():
        if value.device.type == 'cpu':
            cpu_tensors.append(key)
        else:
            cuda_tensors.append(key)

    if cpu_tensors:
        print(f"WARNING: Found {len(cpu_tensors)} tensors on CPU:")
        for key in cpu_tensors[:10]:  # Show first 10
            print(f"  - {key}")
        if len(cpu_tensors) > 10:
            print(f"  ... and {len(cpu_tensors) - 10} more")
    else:
        print(f"All {len(batched_weights)} tensors are on {args.device}")

    # Run tests
    results = {}

    # Always run action decomposition first (needed either way)
    ad_pass, ad_outputs = test_action_decomposition(reference, batched_weights, args.device)
    results['action_decomposition'] = ad_pass

    if args.chain_outputs:
        # Use C++ outputs to chain through embeddings -> gating -> fusion -> transformer -> heads
        emb_pass, emb_outputs = test_embeddings(
            reference, batched_weights, args.device,
            act_kind_ids_override=ad_outputs['act_kind_ids'],
            count_ids_override=ad_outputs['count_ids'],
            table_flag_ids_override=ad_outputs['table_flag_ids'],
        )
        results['embeddings'] = emb_pass

        gating_pass, gating_outputs = test_gating(
            reference, batched_weights, args.device,
            obs_embed_override=emb_outputs['obs_embed'],
            action_embed_override=emb_outputs['action_embed'],
            agent_embed_override=emb_outputs['agent_embed'],
            position_embed_override=emb_outputs['position_embed'],
        )
        results['gating'] = gating_pass

        fusion_pass, fusion_outputs = test_fusion(
            reference, args.device,
            g_obs_override=gating_outputs['g_obs'],
            g_action_override=gating_outputs['g_action'],
            g_agent_override=gating_outputs['g_agent'],
            g_position_override=gating_outputs['g_position'],
            obs_embed_override=emb_outputs['obs_embed'],
            action_embed_override=emb_outputs['action_embed'],
            agent_embed_override=emb_outputs['agent_embed'],
            position_embed_override=emb_outputs['position_embed'],
        )
        results['fusion'] = fusion_pass

        transformer_pass, transformer_output = test_transformer_layers(
            reference, batched_weights, device=args.device,
            fusion_combined=fusion_outputs['combined']
        )
        results['transformer'] = transformer_pass

        results['heads'] = test_heads(
            reference, batched_weights, device=args.device,
            transformer_output=transformer_output
        )
    else:
        # Use reference inputs for each layer (default)
        emb_pass, _ = test_embeddings(reference, batched_weights, args.device)
        results['embeddings'] = emb_pass

        gating_pass, _ = test_gating(reference, batched_weights, args.device)
        results['gating'] = gating_pass

        fusion_pass, _ = test_fusion(reference, args.device)
        results['fusion'] = fusion_pass

        transformer_pass, _ = test_transformer_layers(reference, batched_weights, device=args.device)
        results['transformer'] = transformer_pass

        results['heads'] = test_heads(reference, batched_weights, device=args.device)

    # Return 0 if all passed, 1 if any failed
    return 0 if all(results.values()) else 1


if __name__ == '__main__':
    exit(main())
